name: Linux Kernel Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  KERNEL_VERSION: "4.9.148"
  ARCH: "arm64"
  CROSS_COMPILE: "aarch64-linux-gnu-"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          libncurses-dev \
          bison \
          flex \
          libssl-dev \
          libelf-dev \
          bc \
          git \
          gcc-aarch64-linux-gnu
        
    - name: Set up environment
      run: |
        echo "ARCH=$ARCH" >> $GITHUB_ENV
        echo "CROSS_COMPILE=$CROSS_COMPILE" >> $GITHUB_ENV
        
    - name: Configure kernel
      run: |
        make ARCH=$ARCH defconfig
        
    - name: Build kernel
      run: |
        make ARCH=$ARCH -j$(nproc)
        
    - name: Build modules
      run: |
        make ARCH=$ARCH modules -j$(nproc)
        
    - name: Install modules
      run: |
        sudo make ARCH=$ARCH modules_install INSTALL_MOD_PATH=./modules
        
    - name: Package kernel image
      run: |
        mkdir -p artifacts
        cp arch/$ARCH/boot/Image artifacts/
        tar czvf artifacts/modules.tar.gz -C modules .
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: kernel-build-${{ env.KERNEL_VERSION }}
        path: |
          artifacts/Image
          artifacts/modules.tar.gz
